CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar(15) NOT NULL,
  "last_name" varchar(15) NOT NULL,
  "password" varchar(8) NOT NULL,
  "email" varchar(30) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "machines" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) NOT NULL,
  "user_owner" integer NOT NULL,
  "description" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "machines" ADD FOREIGN KEY ("user_owner") REFERENCES "users" ("id");
