// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
)

type Machine struct {
	ID          int32
	Name        sql.NullString
	UserOwner   sql.NullInt32
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type User struct {
	ID        int32
	FirstName sql.NullString
	LastName  sql.NullString
	Password  sql.NullString
	Email     sql.NullString
	CreatedAt sql.NullTime
}
