// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
)

type Machine struct {
	ID          int32
	Name        string
	UserOwner   int32
	Description string
	CreatedAt   sql.NullTime
}

type User struct {
	ID        int32
	FirstName string
	LastName  string
	Password  string
	Email     string
	CreatedAt sql.NullTime
}
